### ISSUE TITLE
get_lyrics function returning nothing

### ISSUE THREAD

**Issue by GabriWar** [alt-art/genius-rs#12]
code:
```
let lyrics = genius.get_lyrics("https://genius.com/Marty-robbins-big-iron-lyrics").await.unwrap();
    println!("{:#?}", lyrics);
```
result:
`[]`

maybe a i did something wrong? Using the code provided on the readme doesnt seems to help.

**Comment by alt-art** [comment]
As this method is done using web scraping, the web page can change many times.

The version that solves this is not in crates.io, but it may work on your package.toml file [dependencies] session:

```
genius-rs = { git = "https://github.com/alt-art/genius-rs", branch = "master"]
```

I'm sorry that I'm not working on this library anymore because I'm studying, in the future I'll give it the desired attention.

**Comment by alt-art** [comment]
Song struct as a property lyrics, but only can be used with a token with this permission, which if you are not employed by Genius, can only be obtained by reverse engineering.

**Comment by GabriWar** [comment]
dang, yeah, i was messing around with the API and it really sucks that you can't get the lyrics directly from it, thanks for the reply and the nice work, keep it up!

**Comment by alt-art** [comment]
Hey! I was able to solve the problem definitively if it is still interested, I am releasing version 0.5.0.
